### ISSUE TITLE
Esp32 crash during smart lock pairing

### ISSUE THREAD

**Issue by niahane** [uriyacovy/ESPHome_nuki_lock#24]
I do my tests with 2 diffrent esp32 board, an olimex-poe and a esp32-wroom devkit c4.
Latest esphome stable version (2023.3.1) and latest home assistant version.

I also downgraded my esphome addon from 2023.3.1 to 2023.2.4 but nothing change.

Esphome wireless log not reporting nothing interensting.

I have connected my esp32 board to pc and start log from usb tty, now i have a decent log:

[ 36791][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 37287][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 37789][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 38291][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 38787][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 39289][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 39791][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND

IN THIS MOMENT I HAVE TRIGGERED NUKI PAIRING BUTTON:

connectBle retry 0
pairNuki: connectBle success after 986 ms
sendPlainMessage: connectBle success after 0 ms
E (54104) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (54104) task_wdt: - loopTask (CPU 1)
E (54104) task_wdt: Tasks currently running:
E (54104) task_wdt: CPU 0: IDLE
E (54104) task_wdt: CPU 1: IDLE
E (54104) task_wdt: Aborting.

abort() was called at PC 0x400fe824 on core 0

Backtrace:0x40083709:0x3ffbea0c |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:258]: Log initialized
[C][ota:469]: There have been 6 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[I][nukilock.lock:084]: Starting NUKI Lock...
[ 348][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[W][nukilock.lock:109]: ���? Nuki is not paired
[D][binary_sensor:034]: 'Nuki Paired': Sending initial state OFF
[D][lock:055]: 'Nuki Lock': Sending state UNKNOWN
[C][wifi:037]: Setting up WiFi...
[C][wifi:038]: Local MAC: 7C:9E:BD:30:19:74
[D][wifi:386]: Starting scan...
[ 416][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 720][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 1220][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 1720][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 2220][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 2720][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND
[ 3220][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: bleAddress NOT_FOUND

When i trigger pairing all of my Esp32 boards crash :'(

With the same esp32boards i do some test with this project:
https://github.com/technyon/nuki_hub

Everything works as expected, but for me is not a goal, i love esphome instead MQTT. Please tell me if i can help you for testing possible changes in the code.

**Comment by uriyacovy** [comment]
I just updated the dependencies, can you check again with the instructions from here?
https://github.com/uriyacovy/ESPHome_nuki_lock/issues/23#issuecomment-1481069905
