### ISSUE TITLE
Trigger door open when already open

### ISSUE THREAD

**Issue by stefanschaedeli** [uriyacovy/ESPHome_nuki_lock#29]
I have a door without a handle outside, so I would need to send an open command when the door is unlocked. Nuki is then opening the door fully (would allow my to let people in remotely).
I the Nuki app this is possible, but in this inegration I can only toggle between locked and unlocked.

**Comment by uriyacovy** [comment]
This is done with open service. See here: https://github.com/uriyacovy/ESPHome_nuki_lock/issues/1
I'll update the documentation.

**Comment by stefanschaedeli** [comment]
@uriyacovy thanks and sorry :D I'm still confused why home assisten does not add this to the gui of the entity but ok :D works like a charm now!!
