### ISSUE TITLE
NimBLEDevice.h: No such file or directory

### ISSUE THREAD

**Issue by jrnas** [uriyacovy/ESPHome_nuki_lock#43]
hi NimBLEDevice.h is not found at latest esphome version.

In file included from .piolibdeps/esp32-nuki/NukiBleEsp/src/NukiLock.h:3,
                 from src/esphome/components/nuki_lock/nuki_lock.h:10,
                 from src/esphome/components/nuki_lock/nuki_lock.cpp:2:
.piolibdeps/esp32-nuki/NukiBleEsp/src/NukiBle.h:14:10: fatal error: NimBLEDevice.h: No such file or directory

**Comment by marioedani** [comment]
Same here

**Comment by marioedani** [comment]
Solution [here](https://github.com/uriyacovy/ESPHome_nuki_lock/issues/44#issuecomment-2118838202)
Bye

**Comment by uriyacovy** [comment]
Solved in rel v0.0.3.
