### ISSUE TITLE
Questions, not issues

### ISSUE THREAD

**Issue by coxtor** [uriyacovy/ESPHome_nuki_lock#62]
Hi all, thanks for the recent acitivty in this project. 

I was wondering how does the esphome implementation compare to the nuki hub project performance and reliability wise?

Is it possible to use the btproxy, ble_scanner option or even bermuda triangulation alongside with this integration?

Cheers

**Comment by AzonInc** [comment]
Unfortunately using esphome with Niki Component and BT Proxy does not work as this component is using the NimBLE Stack and ESPHome is having another implementation.
